#!/bin/sh

elasticdump \
    --input=http://elasticsearch:9200/candidats \
    --output=$ELASTICSEARCH_BACKUP_DIR/dump-candidats-`date +%Y-%m-%d"_"%H_%M_%S`.json \
    --type=data

gzip $ELASTICSEARCH_BACKUP_DIR/dump-candidats-*.json

# Nettoyage des anciens backups
find $ELASTICSEARCH_BACKUP_DIR/ -mtime +$BACKUP_ROTATION_DAYS -type f -exec rm {} \;

# Synchronise vers un autre répertoire que l'on pourra monter vers une machine distante pour avoir une sauvegarde (en plus de la sauvegarde locale)
rsync -vd $ELASTICSEARCH_BACKUP_DIR/ $ELASTICSEARCH_BACKUP_REMOTE_DIR/
