package fr.poleemploi.perspectives.metier.infra.ws

import fr.poleemploi.perspectives.commun.domain.{CodeROME, CodeSecteurActivite}
import fr.poleemploi.perspectives.commun.infra.ws.{AccessToken, AccessTokenResponse, WSAdapter}
import fr.poleemploi.perspectives.metier.domain.{Metier, ReferentielMetier, SecteurActivite}
import fr.poleemploi.perspectives.metier.infra.elasticsearch.ReferentielMetierElasticsearchAdapter
import play.api.cache.AsyncCacheApi
import play.api.libs.json.{JsError, JsSuccess, JsValue, Json}
import play.api.libs.ws.WSClient

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

/**
  * Se base sur l'API infotravail de l'emploi store. <br />
  * Charge le contenu des métiers en local au cas où l'API n'est pas dispo. (le contenu change très peu)
  */
class ReferentielMetierWSAdapter(config: ReferentielMetierWSAdapterConfig,
                                 mapping: ReferentielMetierWSMapping,
                                 cacheApi: AsyncCacheApi,
                                 wsClient: WSClient,
                                 elasticsearchAdapter: ReferentielMetierElasticsearchAdapter) extends ReferentielMetier with WSAdapter {

  private val metiersResourceId = "767d0c4a-277b-493c-84b7-00143933efce"
  private val cacheKeyMetiers = "referentiel.metiers"

  lazy val metiers: Map[CodeROME, Metier] =
    Json.fromJson[List[Metier]](ReferentielMetierWSAdapter.metiers) match {
      case s: JsSuccess[List[Metier]] =>
        s.value.foldLeft(Map[CodeROME, Metier]())(
          (map, json) => map + (json.codeROME -> Metier(codeROME = json.codeROME, label = json.label))
        )
      case e: JsError => throw new RuntimeException(s"Impossible de charger les métiers du referentiel : $e")
    }

  override def metierParCodeROME(codeROME: CodeROME): Future[Metier] =
    findMetiers.map(metiers => metiers.getOrElse(codeROME, throw new IllegalArgumentException(s"Aucun métier associé au code : ${codeROME.value}")))

  override def metiersParCodesROME(codesROME: Set[CodeROME]): Future[Set[Metier]] =
    findMetiers.map(metiers =>
      codesROME.map(c => metiers.getOrElse(c, throw new IllegalArgumentException(s"Aucun métier associé au code : ${c.value}")))
    )

  override def secteursActivitesRecherche: Future[List[SecteurActivite]] =
    elasticsearchAdapter.secteursActivites

  override def metiersRechercheParCodeROME(codesROME: Set[CodeROME]): Future[Set[Metier]] =
    secteursActivitesRecherche.map(_.flatMap(_.metiers).filter(m => codesROME.contains(m.codeROME)).toSet)

  override def secteurActiviteRechercheParCode(codeSecteurActivite: CodeSecteurActivite): Future[SecteurActivite] =
    secteursActivitesRecherche.map(_.find(s => codeSecteurActivite == s.code).getOrElse(throw new IllegalArgumentException(s"Aucun secteur d'activité associé au code ${codeSecteurActivite.value}")))

  private def findMetiers: Future[Map[CodeROME, Metier]] =
    cacheApi.getOrElseUpdate(cacheKeyMetiers)(
      (for {
        accessTokenResponse <- genererAccessToken
        metiers <- listerMetiers(accessTokenResponse.accessToken)
      } yield metiers).recoverWith {
        case t: Throwable =>
          referentielMetierWSLogger.error("Erreur lors de la récupération des métiers depuis le référentiel", t)
          Future.successful(metiers)
      }
    )

  private def genererAccessToken: Future[AccessTokenResponse] =
    wsClient
      .url(s"${config.urlAuthentification}/connexion/oauth2/access_token?realm=%2F${config.realm}")
      .post(Map(
        "grant_type" -> "client_credentials",
        "client_id" -> config.clientId,
        "client_secret" -> config.clientSecret,
        "scope" -> s"application_${config.clientId} api_infotravailv1",
      ))
      .flatMap(filtreStatutReponse(_))
      .map(_.json.as[AccessTokenResponse])

  private def listerMetiers(accessToken: AccessToken): Future[Map[CodeROME, Metier]] = {
    def callWS(offset: Option[Int] = None): Future[ListeMetiersResponse] =
      wsClient
        .url(s"${config.urlApi}/infotravail/v1/datastore_search" +
          offset.map(o => s"?offset=$o&resource_id=$metiersResourceId")
            .getOrElse(s"?resource_id=$metiersResourceId"))
        .addHttpHeaders(authorizationBearer(accessToken))
        .get()
        .flatMap(filtreStatutReponse(_))
        .map(_.json.as[ListeMetiersResponse])

    val futures = callWS().flatMap { listeMetiers =>
      val nbRecordsParPage = listeMetiers.records.size
      val nbPages = Math.floor(listeMetiers.total / nbRecordsParPage)

      Future.sequence(Future.successful(listeMetiers) :: List.tabulate(nbPages.toInt)(n =>
        callWS(offset = Some((n + 1) * nbRecordsParPage))
      ))
    }

    futures.map { l =>
      l.flatMap(_.records)
        .foldLeft(Map[CodeROME, Metier]())(
          (map, romeCardResponse) =>
            map + (CodeROME(romeCardResponse.romeProfessionCardCode) -> mapping.buildMetier(romeCardResponse))
        )
    }
  }
}

object ReferentielMetierWSAdapter {

  lazy val metiers: JsValue = Json.parse(
    s"""
       |[
       |  {"codeROME": "A1204", "label": "Protection du patrimoine naturel"},
       |  {"codeROME": "D1214", "label": "Vente en habillement et accessoires de la personne"},
       |  {"codeROME": "D1301", "label": "Management de magasin de d\u00e9tail"},
       |  {"codeROME": "D1401", "label": "Assistanat commercial"},
       |  {"codeROME": "D1402", "label": "Relation commerciale grands comptes et entreprises"},
       |  {"codeROME": "D1403", "label": "Relation commerciale aupr\u00e8s de particuliers"},
       |  {"codeROME": "D1404", "label": "Relation commerciale en vente de v\u00e9hicules"},
       |  {"codeROME": "D1405", "label": "Conseil en information m\u00e9dicale"},
       |  {"codeROME": "D1406", "label": "Management en force de vente"},
       |  {"codeROME": "D1407", "label": "Relation technico-commerciale"},
       |  {"codeROME": "D1408", "label": "T\u00e9l\u00e9conseil et t\u00e9l\u00e9vente"},
       |  {"codeROME": "A1205", "label": "Sylviculture"},
       |  {"codeROME": "D1501", "label": "Animation de vente"},
       |  {"codeROME": "D1502", "label": "Management/gestion de rayon produits alimentaires"},
       |  {"codeROME": "D1503", "label": "Management/gestion de rayon produits non alimentaires"},
       |  {"codeROME": "D1504", "label": "Direction de magasin de grande distribution"},
       |  {"codeROME": "D1505", "label": "Personnel de caisse"},
       |  {"codeROME": "D1506", "label": "Marchandisage"},
       |  {"codeROME": "D1507", "label": "Mise en rayon libre-service"},
       |  {"codeROME": "D1508", "label": "Encadrement du personnel de caisses"},
       |  {"codeROME": "D1509", "label": "Management de d\u00e9partement en grande distribution"},
       |  {"codeROME": "E1101", "label": "Animation de site multim\u00e9dia"},
       |  {"codeROME": "A1301", "label": "Conseil et assistance technique en agriculture"},
       |  {"codeROME": "E1102", "label": "Ecriture d'ouvrages, de livres"},
       |  {"codeROME": "E1103", "label": "Communication"},
       |  {"codeROME": "E1104", "label": "Conception de contenus multim\u00e9dias"},
       |  {"codeROME": "E1105", "label": "Coordination d'\u00e9dition"},
       |  {"codeROME": "E1106", "label": "Journalisme et information m\u00e9dia"},
       |  {"codeROME": "E1107", "label": "Organisation d'\u00e9v\u00e8nementiel"},
       |  {"codeROME": "E1108", "label": "Traduction, interpr\u00e9tariat"},
       |  {"codeROME": "E1201", "label": "Photographie"},
       |  {"codeROME": "E1202", "label": "Production en laboratoire cin\u00e9matographique"},
       |  {"codeROME": "E1203", "label": "Production en laboratoire photographique"},
       |  {"codeROME": "A1302", "label": "Contr\u00f4le et diagnostic technique en agriculture"},
       |  {"codeROME": "E1204", "label": "Projection cin\u00e9ma"},
       |  {"codeROME": "E1205", "label": "R\u00e9alisation de contenus multim\u00e9dias"},
       |  {"codeROME": "E1301", "label": "Conduite de machines d'impression"},
       |  {"codeROME": "E1302", "label": "Conduite de machines de fa\u00e7onnage routage"},
       |  {"codeROME": "E1303", "label": "Encadrement des industries graphiques"},
       |  {"codeROME": "E1304", "label": "Fa\u00e7onnage et routage"},
       |  {"codeROME": "E1305", "label": "Pr\u00e9paration et correction en \u00e9dition et presse"},
       |  {"codeROME": "E1306", "label": "Pr\u00e9presse"},
       |  {"codeROME": "E1307", "label": "Reprographie"},
       |  {"codeROME": "E1308", "label": "Intervention technique en industrie graphique"},
       |  {"codeROME": "A1303", "label": "Ing\u00e9nierie en agriculture et environnement naturel"},
       |  {"codeROME": "E1401", "label": "D\u00e9veloppement et promotion publicitaire"},
       |  {"codeROME": "E1402", "label": "\u00c9laboration de plan m\u00e9dia"},
       |  {"codeROME": "F1101", "label": "Architecture du BTP et du paysage"},
       |  {"codeROME": "F1102", "label": "Conception - am\u00e9nagement d'espaces int\u00e9rieurs"},
       |  {"codeROME": "F1103", "label": "Contr\u00f4le et diagnostic technique du b\u00e2timent"},
       |  {"codeROME": "F1104", "label": "Dessin BTP et paysage"},
       |  {"codeROME": "F1105", "label": "\u00c9tudes g\u00e9ologiques"},
       |  {"codeROME": "F1106", "label": "Ing\u00e9nierie et \u00e9tudes du BTP"},
       |  {"codeROME": "F1107", "label": "Mesures topographiques"},
       |  {"codeROME": "F1108", "label": "M\u00e9tr\u00e9 de la construction"},
       |  {"codeROME": "A1401", "label": "Aide agricole de production fruiti\u00e8re ou viticole"},
       |  {"codeROME": "F1201", "label": "Conduite de travaux du BTP et de travaux paysagers"},
       |  {"codeROME": "F1202", "label": "Direction de chantier du BTP"},
       |  {"codeROME": "F1203", "label": "Direction et ing\u00e9nierie d'exploitation de gisements et de carri\u00e8res"},
       |  {"codeROME": "F1204", "label": "Qualit\u00e9 S\u00e9curit\u00e9 Environnement et protection sant\u00e9 du BTP"},
       |  {"codeROME": "F1301", "label": "Conduite de grue"},
       |  {"codeROME": "F1302", "label": "Conduite d'engins de terrassement et de carri\u00e8re"},
       |  {"codeROME": "F1401", "label": "Extraction liquide et gazeuse"},
       |  {"codeROME": "F1402", "label": "Extraction solide"},
       |  {"codeROME": "F1501", "label": "Montage de structures et de charpentes bois"},
       |  {"codeROME": "F1502", "label": "Montage de structures m\u00e9talliques"},
       |  {"codeROME": "A1402", "label": "Aide agricole de production l\u00e9gumi\u00e8re ou v\u00e9g\u00e9tale"},
       |  {"codeROME": "F1503", "label": "R\u00e9alisation - installation d'ossatures bois"},
       |  {"codeROME": "F1601", "label": "Application et d\u00e9coration en pl\u00e2tre, stuc et staff"},
       |  {"codeROME": "F1602", "label": "\u00c9lectricit\u00e9 b\u00e2timent"},
       |  {"codeROME": "F1603", "label": "Installation d'\u00e9quipements sanitaires et thermiques"},
       |  {"codeROME": "F1604", "label": "Montage d'agencements"},
       |  {"codeROME": "F1605", "label": "Montage de r\u00e9seaux \u00e9lectriques et t\u00e9l\u00e9coms"},
       |  {"codeROME": "F1606", "label": "Peinture en b\u00e2timent"},
       |  {"codeROME": "F1607", "label": "Pose de fermetures menuis\u00e9es"},
       |  {"codeROME": "F1608", "label": "Pose de rev\u00eatements rigides"},
       |  {"codeROME": "F1609", "label": "Pose de rev\u00eatements souples"},
       |  {"codeROME": "A1403", "label": "Aide d'\u00e9levage agricole et aquacole"},
       |  {"codeROME": "F1610", "label": "Pose et restauration de couvertures"},
       |  {"codeROME": "F1611", "label": "R\u00e9alisation et restauration de fa\u00e7ades"},
       |  {"codeROME": "F1612", "label": "Taille et d\u00e9coration de pierres"},
       |  {"codeROME": "F1613", "label": "Travaux d'\u00e9tanch\u00e9it\u00e9 et d'isolation"},
       |  {"codeROME": "F1701", "label": "Construction en b\u00e9ton"},
       |  {"codeROME": "F1702", "label": "Construction de routes et voies"},
       |  {"codeROME": "F1703", "label": "Ma\u00e7onnerie"},
       |  {"codeROME": "F1704", "label": "Pr\u00e9paration du gros oeuvre et des travaux publics"},
       |  {"codeROME": "F1705", "label": "Pose de canalisations"},
       |  {"codeROME": "F1706", "label": "Pr\u00e9fabrication en b\u00e9ton industriel"},
       |  {"codeROME": "A1404", "label": "Aquaculture"},
       |  {"codeROME": "G1101", "label": "Accueil touristique"},
       |  {"codeROME": "G1102", "label": "Promotion du tourisme local"},
       |  {"codeROME": "G1201", "label": "Accompagnement de voyages, d'activit\u00e9s culturelles ou sportives"},
       |  {"codeROME": "G1202", "label": "Animation d'activit\u00e9s culturelles ou ludiques"},
       |  {"codeROME": "G1203", "label": "Animation de loisirs aupr\u00e8s d'enfants ou d'adolescents"},
       |  {"codeROME": "G1204", "label": "\u00c9ducation en activit\u00e9s sportives"},
       |  {"codeROME": "G1205", "label": "Personnel d'attractions ou de structures de loisirs"},
       |  {"codeROME": "G1206", "label": "Personnel technique des jeux"},
       |  {"codeROME": "G1301", "label": "Conception de produits touristiques"},
       |  {"codeROME": "G1302", "label": "Optimisation de produits touristiques"},
       |  {"codeROME": "A1405", "label": "Arboriculture et viticulture"},
       |  {"codeROME": "G1303", "label": "Vente de voyages"},
       |  {"codeROME": "G1401", "label": "Assistance de direction d'h\u00f4tel-restaurant"},
       |  {"codeROME": "G1402", "label": "Management d'h\u00f4tel-restaurant"},
       |  {"codeROME": "G1403", "label": "Gestion de structure de loisirs ou d'h\u00e9bergement touristique"},
       |  {"codeROME": "G1404", "label": "Management d'\u00e9tablissement de restauration collective"},
       |  {"codeROME": "G1501", "label": "Personnel d'\u00e9tage"},
       |  {"codeROME": "G1502", "label": "Personnel polyvalent d'h\u00f4tellerie"},
       |  {"codeROME": "G1503", "label": "Management du personnel d'\u00e9tage"},
       |  {"codeROME": "G1601", "label": "Management du personnel de cuisine"},
       |  {"codeROME": "G1602", "label": "Personnel de cuisine"},
       |  {"codeROME": "A1406", "label": "Encadrement \u00e9quipage de la p\u00eache"},
       |  {"codeROME": "G1603", "label": "Personnel polyvalent en restauration"},
       |  {"codeROME": "G1604", "label": "Fabrication de cr\u00eapes ou pizzas"},
       |  {"codeROME": "G1605", "label": "Plonge en restauration"},
       |  {"codeROME": "G1701", "label": "Conciergerie en h\u00f4tellerie"},
       |  {"codeROME": "G1702", "label": "Personnel du hall"},
       |  {"codeROME": "G1703", "label": "R\u00e9ception en h\u00f4tellerie"},
       |  {"codeROME": "G1801", "label": "Caf\u00e9, bar brasserie"},
       |  {"codeROME": "G1802", "label": "Management du service en restauration"},
       |  {"codeROME": "G1803", "label": "Service en restauration"},
       |  {"codeROME": "G1804", "label": "Sommellerie"},
       |  {"codeROME": "A1407", "label": "\u00c9levage bovin ou \u00e9quin"},
       |  {"codeROME": "H1101", "label": "Assistance et support technique client"},
       |  {"codeROME": "H1102", "label": "Management et ing\u00e9nierie d'affaires"},
       |  {"codeROME": "H1201", "label": "Expertise technique couleur en industrie"},
       |  {"codeROME": "H1202", "label": "Conception et dessin de produits \u00e9lectriques et \u00e9lectroniques"},
       |  {"codeROME": "H1203", "label": "Conception et dessin produits m\u00e9caniques"},
       |  {"codeROME": "H1204", "label": "Design industriel"},
       |  {"codeROME": "H1205", "label": "\u00c9tudes - mod\u00e8les en industrie des mat\u00e9riaux souples"},
       |  {"codeROME": "H1206", "label": "Management et ing\u00e9nierie \u00e9tudes, recherche et d\u00e9veloppement industriel"},
       |  {"codeROME": "H1207", "label": "R\u00e9daction technique"},
       |  {"codeROME": "H1208", "label": "Intervention technique en \u00e9tudes et conception en automatisme"},
       |  {"codeROME": "A1408", "label": "\u00c9levage d'animaux sauvages ou de compagnie"},
       |  {"codeROME": "H1209", "label": "Intervention technique en \u00e9tudes et d\u00e9veloppement \u00e9lectronique"},
       |  {"codeROME": "H1210", "label": "Intervention technique en \u00e9tudes, recherche et d\u00e9veloppement"},
       |  {"codeROME": "H1301", "label": "Inspection de conformit\u00e9"},
       |  {"codeROME": "H1302", "label": "Management et ing\u00e9nierie Hygi\u00e8ne S\u00e9curit\u00e9 Environnement -HSE- industriels"},
       |  {"codeROME": "H1303", "label": "Intervention technique en Hygi\u00e8ne S\u00e9curit\u00e9 Environnement -HSE- industriel"},
       |  {"codeROME": "H1401", "label": "Management et ing\u00e9nierie gestion industrielle et logistique"},
       |  {"codeROME": "H1402", "label": "Management et ing\u00e9nierie m\u00e9thodes et industrialisation"},
       |  {"codeROME": "H1403", "label": "Intervention technique en gestion industrielle et logistique"},
       |  {"codeROME": "H1404", "label": "Intervention technique en m\u00e9thodes et industrialisation"},
       |  {"codeROME": "H1501", "label": "Direction de laboratoire d'analyse industrielle"},
       |  {"codeROME": "A1409", "label": "\u00c9levage de lapins et volailles"},
       |  {"codeROME": "H1502", "label": "Management et ing\u00e9nierie qualit\u00e9 industrielle"},
       |  {"codeROME": "H1503", "label": "Intervention technique en laboratoire d'analyse industrielle"},
       |  {"codeROME": "H1504", "label": "Intervention technique en contr\u00f4le essai qualit\u00e9 en \u00e9lectricit\u00e9 et \u00e9lectronique"},
       |  {"codeROME": "H1505", "label": "Intervention technique en formulation et analyse sensorielle"},
       |  {"codeROME": "H1506", "label": "Intervention technique qualit\u00e9 en m\u00e9canique et travail des m\u00e9taux"},
       |  {"codeROME": "H2101", "label": "Abattage et d\u00e9coupe des viandes"},
       |  {"codeROME": "H2102", "label": "Conduite d'\u00e9quipement de production alimentaire"},
       |  {"codeROME": "H2201", "label": "Assemblage d'ouvrages en bois"},
       |  {"codeROME": "H2202", "label": "Conduite d'\u00e9quipement de fabrication de l'ameublement et du bois"},
       |  {"codeROME": "H2203", "label": "Conduite d'installation de production de panneaux bois"},
       |  {"codeROME": "A1410", "label": "\u00c9levage ovin ou caprin"},
       |  {"codeROME": "H2204", "label": "Encadrement des industries de l'ameublement et du bois"},
       |  {"codeROME": "H2205", "label": "Premi\u00e8re transformation de bois d'oeuvre"},
       |  {"codeROME": "H2206", "label": "R\u00e9alisation de menuiserie bois et tonnellerie"},
       |  {"codeROME": "H2207", "label": "R\u00e9alisation de meubles en bois"},
       |  {"codeROME": "H2208", "label": "R\u00e9alisation d'ouvrages d\u00e9coratifs en bois"},
       |  {"codeROME": "H2209", "label": "Intervention technique en ameublement et bois"},
       |  {"codeROME": "H2301", "label": "Conduite d'\u00e9quipement de production chimique ou pharmaceutique"},
       |  {"codeROME": "H2401", "label": "Assemblage - montage d'articles en cuirs, peaux"},
       |  {"codeROME": "H2402", "label": "Assemblage - montage de v\u00eatements et produits textiles"},
       |  {"codeROME": "H2403", "label": "Conduite de machine de fabrication de produits textiles"},
       |  {"codeROME": "A1411", "label": "\u00c9levage porcin"},
       |  {"codeROME": "H2404", "label": "Conduite de machine de production et transformation des fils"},
       |  {"codeROME": "H2405", "label": "Conduite de machine de textiles nontiss\u00e9s"},
       |  {"codeROME": "H2406", "label": "Conduite de machine de traitement textile"},
       |  {"codeROME": "H2407", "label": "Conduite de machine de transformation et de finition des cuirs et peaux"},
       |  {"codeROME": "H2408", "label": "Conduite de machine d'impression textile"},
       |  {"codeROME": "H2409", "label": "Coupe cuir, textile et mat\u00e9riaux souples"},
       |  {"codeROME": "H2410", "label": "Mise en forme, repassage et finitions en industrie textile"},
       |  {"codeROME": "H2411", "label": "Montage de prototype cuir et mat\u00e9riaux souples"},
       |  {"codeROME": "H2412", "label": "Patronnage - gradation"},
       |  {"codeROME": "H2413", "label": "Pr\u00e9paration de fils, montage de m\u00e9tiers textiles"},
       |  {"codeROME": "A1412", "label": "Fabrication et affinage de fromages"},
       |  {"codeROME": "H2414", "label": "Pr\u00e9paration et finition d'articles en cuir et mat\u00e9riaux souples"},
       |  {"codeROME": "H2415", "label": "Contr\u00f4le en industrie du cuir et du textile"},
       |  {"codeROME": "H2501", "label": "Encadrement de production de mat\u00e9riel \u00e9lectrique et \u00e9lectronique"},
       |  {"codeROME": "H2502", "label": "Management et ing\u00e9nierie de production"},
       |  {"codeROME": "H2503", "label": "Pilotage d'unit\u00e9 \u00e9l\u00e9mentaire de production m\u00e9canique ou de travail des m\u00e9taux"},
       |  {"codeROME": "H2504", "label": "Encadrement d'\u00e9quipe en industrie de transformation"},
       |  {"codeROME": "H2505", "label": "Encadrement d'\u00e9quipe ou d'atelier en mat\u00e9riaux souples"},
       |  {"codeROME": "H2601", "label": "Bobinage \u00e9lectrique"},
       |  {"codeROME": "H2602", "label": "C\u00e2blage \u00e9lectrique et \u00e9lectrom\u00e9canique"},
       |  {"codeROME": "H2603", "label": "Conduite d'installation automatis\u00e9e de production \u00e9lectrique, \u00e9lectronique et micro\u00e9lectronique"},
       |  {"codeROME": "A1413", "label": "Fermentation de boissons alcoolis\u00e9es"},
       |  {"codeROME": "H2604", "label": "Montage de produits \u00e9lectriques et \u00e9lectroniques"},
       |  {"codeROME": "H2605", "label": "Montage et c\u00e2blage \u00e9lectronique"},
       |  {"codeROME": "H2701", "label": "Pilotage d'installation \u00e9nerg\u00e9tique et p\u00e9trochimique"},
       |  {"codeROME": "H2801", "label": "Conduite d'\u00e9quipement de transformation du verre"},
       |  {"codeROME": "H2802", "label": "Conduite d'installation de production de mat\u00e9riaux de construction"},
       |  {"codeROME": "H2803", "label": "Fa\u00e7onnage et \u00e9maillage en industrie c\u00e9ramique"},
       |  {"codeROME": "H2804", "label": "Pilotage de centrale \u00e0 b\u00e9ton pr\u00eat \u00e0 l'emploi, ciment, enrob\u00e9s et granulats"},
       |  {"codeROME": "H2805", "label": "Pilotage d'installation de production verri\u00e8re"},
       |  {"codeROME": "H2901", "label": "Ajustement et montage de fabrication"},
       |  {"codeROME": "H2902", "label": "Chaudronnerie - t\u00f4lerie"},
       |  {"codeROME": "A1414", "label": "Horticulture et mara\u00eechage"},
       |  {"codeROME": "H2903", "label": "Conduite d'\u00e9quipement d'usinage"},
       |  {"codeROME": "H2904", "label": "Conduite d'\u00e9quipement de d\u00e9formation des m\u00e9taux"},
       |  {"codeROME": "H2905", "label": "Conduite d'\u00e9quipement de formage et d\u00e9coupage des mat\u00e9riaux"},
       |  {"codeROME": "H2906", "label": "Conduite d'installation automatis\u00e9e ou robotis\u00e9e de fabrication m\u00e9canique"},
       |  {"codeROME": "H2907", "label": "Conduite d'installation de production des m\u00e9taux"},
       |  {"codeROME": "H2908", "label": "Modelage de mat\u00e9riaux non m\u00e9talliques"},
       |  {"codeROME": "H2909", "label": "Montage-assemblage m\u00e9canique"},
       |  {"codeROME": "H2910", "label": "Moulage sable"},
       |  {"codeROME": "H2911", "label": "R\u00e9alisation de structures m\u00e9talliques"},
       |  {"codeROME": "H2912", "label": "R\u00e9glage d'\u00e9quipement de production industrielle"},
       |  {"codeROME": "K1305", "label": "Intervention sociale et familiale"},
       |  {"codeROME": "A1415", "label": "Equipage de la p\u00eache"},
       |  {"codeROME": "H2913", "label": "Soudage manuel"},
       |  {"codeROME": "H2914", "label": "R\u00e9alisation et montage en tuyauterie"},
       |  {"codeROME": "H3101", "label": "Conduite d'\u00e9quipement de fabrication de papier ou de carton"},
       |  {"codeROME": "H3102", "label": "Conduite d'installation de p\u00e2te \u00e0 papier"},
       |  {"codeROME": "I1601", "label": "Installation et maintenance en nautisme"},
       |  {"codeROME": "H3201", "label": "Conduite d'\u00e9quipement de formage des plastiques et caoutchoucs"},
       |  {"codeROME": "H3202", "label": "R\u00e9glage d'\u00e9quipement de formage des plastiques et caoutchoucs"},
       |  {"codeROME": "H3203", "label": "Fabrication de pi\u00e8ces en mat\u00e9riaux composites"},
       |  {"codeROME": "H3301", "label": "Conduite d'\u00e9quipement de conditionnement"},
       |  {"codeROME": "H3302", "label": "Op\u00e9rations manuelles d'assemblage, tri ou emballage"},
       |  {"codeROME": "H3303", "label": "Pr\u00e9paration de mati\u00e8res et produits industriels (broyage, m\u00e9lange, ...)"},
       |  {"codeROME": "A1416", "label": "Polyculture, \u00e9levage"},
       |  {"codeROME": "H3401", "label": "Conduite de traitement d'abrasion de surface"},
       |  {"codeROME": "H3402", "label": "Conduite de traitement par d\u00e9p\u00f4t de surface"},
       |  {"codeROME": "H3403", "label": "Conduite de traitement thermique"},
       |  {"codeROME": "H3404", "label": "Peinture industrielle"},
       |  {"codeROME": "I1101", "label": "Direction et ing\u00e9nierie en entretien infrastructure et b\u00e2ti"},
       |  {"codeROME": "I1102", "label": "Management et ing\u00e9nierie de maintenance industrielle"},
       |  {"codeROME": "I1103", "label": "Supervision d'entretien et gestion de v\u00e9hicules"},
       |  {"codeROME": "I1201", "label": "Entretien d'affichage et mobilier urbain"},
       |  {"codeROME": "I1202", "label": "Entretien et surveillance du trac\u00e9 routier"},
       |  {"codeROME": "I1203", "label": "Maintenance des b\u00e2timents et des locaux"},
       |  {"codeROME": "A1417", "label": "Saliculture"},
       |  {"codeROME": "I1301", "label": "Installation et maintenance d'ascenseurs"},
       |  {"codeROME": "I1302", "label": "Installation et maintenance d'automatismes"},
       |  {"codeROME": "I1303", "label": "Installation et maintenance de distributeurs automatiques"},
       |  {"codeROME": "I1304", "label": "Installation et maintenance d'\u00e9quipements industriels et d'exploitation"},
       |  {"codeROME": "I1305", "label": "Installation et maintenance \u00e9lectronique"},
       |  {"codeROME": "I1306", "label": "Installation et maintenance en froid, conditionnement d'air"},
       |  {"codeROME": "I1307", "label": "Installation et maintenance t\u00e9l\u00e9coms et courants faibles"},
       |  {"codeROME": "I1308", "label": "Maintenance d'installation de chauffage"},
       |  {"codeROME": "I1309", "label": "Maintenance \u00e9lectrique"},
       |  {"codeROME": "I1310", "label": "Maintenance m\u00e9canique industrielle"},
       |  {"codeROME": "A1501", "label": "Aide aux soins animaux"},
       |  {"codeROME": "I1401", "label": "Maintenance informatique et bureautique"},
       |  {"codeROME": "I1402", "label": "R\u00e9paration de biens \u00e9lectrodomestiques et multim\u00e9dia"},
       |  {"codeROME": "I1501", "label": "Intervention en grande hauteur"},
       |  {"codeROME": "I1502", "label": "Intervention en milieu subaquatique"},
       |  {"codeROME": "I1503", "label": "Intervention en milieux et produits nocifs"},
       |  {"codeROME": "I1602", "label": "Maintenance d'a\u00e9ronefs"},
       |  {"codeROME": "I1603", "label": "Maintenance d'engins de chantier, levage, manutention et de machines agricoles"},
       |  {"codeROME": "I1604", "label": "M\u00e9canique automobile et entretien de v\u00e9hicules"},
       |  {"codeROME": "I1605", "label": "M\u00e9canique de marine"},
       |  {"codeROME": "A1502", "label": "Podologie animale"},
       |  {"codeROME": "I1606", "label": "R\u00e9paration de carrosserie"},
       |  {"codeROME": "I1607", "label": "R\u00e9paration de cycles, motocycles et motoculteurs de loisirs"},
       |  {"codeROME": "J1101", "label": "M\u00e9decine de pr\u00e9vention"},
       |  {"codeROME": "J1102", "label": "M\u00e9decine g\u00e9n\u00e9raliste et sp\u00e9cialis\u00e9e"},
       |  {"codeROME": "J1103", "label": "M\u00e9decine dentaire"},
       |  {"codeROME": "J1104", "label": "Suivi de la grossesse et de l'accouchement"},
       |  {"codeROME": "J1201", "label": "Biologie m\u00e9dicale"},
       |  {"codeROME": "J1202", "label": "Pharmacie"},
       |  {"codeROME": "J1301", "label": "Personnel polyvalent des services hospitaliers"},
       |  {"codeROME": "J1302", "label": "Analyses m\u00e9dicales"},
       |  {"codeROME": "A1503", "label": "Toilettage des animaux"},
       |  {"codeROME": "J1303", "label": "Assistance m\u00e9dico-technique"},
       |  {"codeROME": "J1304", "label": "Aide en pu\u00e9riculture"},
       |  {"codeROME": "J1305", "label": "Conduite de v\u00e9hicules sanitaires"},
       |  {"codeROME": "J1306", "label": "Imagerie m\u00e9dicale"},
       |  {"codeROME": "J1307", "label": "Pr\u00e9paration en pharmacie"},
       |  {"codeROME": "J1401", "label": "Audioproth\u00e8ses"},
       |  {"codeROME": "J1402", "label": "Di\u00e9t\u00e9tique"},
       |  {"codeROME": "J1403", "label": "Ergoth\u00e9rapie"},
       |  {"codeROME": "J1404", "label": "Kin\u00e9sith\u00e9rapie"},
       |  {"codeROME": "J1405", "label": "Optique - lunetterie"},
       |  {"codeROME": "A1504", "label": "Sant\u00e9 animale"},
       |  {"codeROME": "J1406", "label": "Orthophonie"},
       |  {"codeROME": "J1407", "label": "Orthoptique"},
       |  {"codeROME": "J1408", "label": "Ost\u00e9opathie et chiropraxie"},
       |  {"codeROME": "J1409", "label": "P\u00e9dicurie et podologie"},
       |  {"codeROME": "J1410", "label": "Proth\u00e8ses dentaires"},
       |  {"codeROME": "J1411", "label": "Proth\u00e8ses et orth\u00e8ses"},
       |  {"codeROME": "J1412", "label": "R\u00e9\u00e9ducation en psychomotricit\u00e9"},
       |  {"codeROME": "J1501", "label": "Soins d'hygi\u00e8ne, de confort du patient"},
       |  {"codeROME": "J1502", "label": "Coordination de services m\u00e9dicaux ou param\u00e9dicaux"},
       |  {"codeROME": "J1503", "label": "Soins infirmiers sp\u00e9cialis\u00e9s en anesth\u00e9sie"},
       |  {"codeROME": "B1101", "label": "Cr\u00e9ation en arts plastiques"},
       |  {"codeROME": "J1504", "label": "Soins infirmiers sp\u00e9cialis\u00e9s en bloc op\u00e9ratoire"},
       |  {"codeROME": "J1505", "label": "Soins infirmiers sp\u00e9cialis\u00e9s en pr\u00e9vention"},
       |  {"codeROME": "J1506", "label": "Soins infirmiers g\u00e9n\u00e9ralistes"},
       |  {"codeROME": "J1507", "label": "Soins infirmiers sp\u00e9cialis\u00e9s en pu\u00e9riculture"},
       |  {"codeROME": "K1101", "label": "Accompagnement et m\u00e9diation familiale"},
       |  {"codeROME": "K1102", "label": "Aide aux b\u00e9n\u00e9ficiaires d'une mesure de protection juridique"},
       |  {"codeROME": "K1103", "label": "D\u00e9veloppement personnel et bien-\u00eatre de la personne"},
       |  {"codeROME": "K1104", "label": "Psychologie"},
       |  {"codeROME": "K1201", "label": "Action sociale"},
       |  {"codeROME": "K1202", "label": "\u00c9ducation de jeunes enfants"},
       |  {"codeROME": "B1201", "label": "R\u00e9alisation d'objets d\u00e9coratifs et utilitaires en c\u00e9ramique et mat\u00e9riaux de synth\u00e8se"},
       |  {"codeROME": "K1203", "label": "Encadrement technique en insertion professionnelle"},
       |  {"codeROME": "K1204", "label": "M\u00e9diation sociale et facilitation de la vie en soci\u00e9t\u00e9"},
       |  {"codeROME": "K1205", "label": "Information sociale"},
       |  {"codeROME": "K1206", "label": "Intervention socioculturelle"},
       |  {"codeROME": "K1207", "label": "Intervention socio\u00e9ducative"},
       |  {"codeROME": "K1301", "label": "Accompagnement m\u00e9dicosocial"},
       |  {"codeROME": "K1302", "label": "Assistance aupr\u00e8s d'adultes"},
       |  {"codeROME": "K1303", "label": "Assistance aupr\u00e8s d'enfants"},
       |  {"codeROME": "K1304", "label": "Services domestiques"},
       |  {"codeROME": "K1401", "label": "Conception et pilotage de la politique des pouvoirs publics"},
       |  {"codeROME": "B1301", "label": "D\u00e9coration d'espaces de vente et d'exposition"},
       |  {"codeROME": "K1402", "label": "Conseil en Sant\u00e9 Publique"},
       |  {"codeROME": "K1403", "label": "Management de structure de sant\u00e9, sociale ou p\u00e9nitentiaire"},
       |  {"codeROME": "K1404", "label": "Mise en oeuvre et pilotage de la politique des pouvoirs publics"},
       |  {"codeROME": "K1405", "label": "Repr\u00e9sentation de l'Etat sur le territoire national ou international"},
       |  {"codeROME": "K1501", "label": "Application des r\u00e8gles financi\u00e8res publiques"},
       |  {"codeROME": "K1502", "label": "Contr\u00f4le et inspection des Affaires Sociales"},
       |  {"codeROME": "K1503", "label": "Contr\u00f4le et inspection des imp\u00f4ts"},
       |  {"codeROME": "K1504", "label": "Contr\u00f4le et inspection du Tr\u00e9sor Public"},
       |  {"codeROME": "K1505", "label": "Protection des consommateurs et contr\u00f4le des \u00e9changes commerciaux"},
       |  {"codeROME": "K1601", "label": "Gestion de l'information et de la documentation"},
       |  {"codeROME": "B1302", "label": "D\u00e9coration d'objets d'art et artisanaux"},
       |  {"codeROME": "K1602", "label": "Gestion de patrimoine culturel"},
       |  {"codeROME": "L1510", "label": "Films d'animation et effets sp\u00e9ciaux"},
       |  {"codeROME": "K1701", "label": "Personnel de la D\u00e9fense"},
       |  {"codeROME": "K1702", "label": "Direction de la s\u00e9curit\u00e9 civile et des secours"},
       |  {"codeROME": "K1703", "label": "Direction op\u00e9rationnelle de la d\u00e9fense"},
       |  {"codeROME": "K1704", "label": "Management de la s\u00e9curit\u00e9 publique"},
       |  {"codeROME": "K1705", "label": "S\u00e9curit\u00e9 civile et secours"},
       |  {"codeROME": "K1706", "label": "S\u00e9curit\u00e9 publique"},
       |  {"codeROME": "K1707", "label": "Surveillance municipale"},
       |  {"codeROME": "K1801", "label": "Conseil en emploi et insertion socioprofessionnelle"},
       |  {"codeROME": "K1802", "label": "D\u00e9veloppement local"},
       |  {"codeROME": "B1303", "label": "Gravure - ciselure"},
       |  {"codeROME": "K1901", "label": "Aide et m\u00e9diation judiciaire"},
       |  {"codeROME": "K1902", "label": "Collaboration juridique"},
       |  {"codeROME": "K1903", "label": "D\u00e9fense et conseil juridique"},
       |  {"codeROME": "K1904", "label": "Magistrature"},
       |  {"codeROME": "K2101", "label": "Conseil en formation"},
       |  {"codeROME": "K2102", "label": "Coordination p\u00e9dagogique"},
       |  {"codeROME": "K2103", "label": "Direction d'\u00e9tablissement et d'enseignement"},
       |  {"codeROME": "K2104", "label": "\u00c9ducation et surveillance au sein d'\u00e9tablissements d'enseignement"},
       |  {"codeROME": "K2105", "label": "Enseignement artistique"},
       |  {"codeROME": "K2106", "label": "Enseignement des \u00e9coles"},
       |  {"codeROME": "B1401", "label": "R\u00e9alisation d'objets en lianes, fibres et brins v\u00e9g\u00e9taux"},
       |  {"codeROME": "K2107", "label": "Enseignement g\u00e9n\u00e9ral du second degr\u00e9"},
       |  {"codeROME": "K2108", "label": "Enseignement sup\u00e9rieur"},
       |  {"codeROME": "K2109", "label": "Enseignement technique et professionnel"},
       |  {"codeROME": "K2110", "label": "Formation en conduite de v\u00e9hicules"},
       |  {"codeROME": "K2111", "label": "Formation professionnelle"},
       |  {"codeROME": "K2112", "label": "Orientation scolaire et professionnelle"},
       |  {"codeROME": "K2201", "label": "Blanchisserie industrielle"},
       |  {"codeROME": "K2202", "label": "Lavage de vitres"},
       |  {"codeROME": "K2203", "label": "Management et inspection en propret\u00e9 de locaux"},
       |  {"codeROME": "K2204", "label": "Nettoyage de locaux"},
       |  {"codeROME": "B1402", "label": "Reliure et restauration de livres et archives"},
       |  {"codeROME": "K2301", "label": "Distribution et assainissement d'eau"},
       |  {"codeROME": "K2302", "label": "Management et inspection en environnement urbain"},
       |  {"codeROME": "K2303", "label": "Nettoyage des espaces urbains"},
       |  {"codeROME": "K2304", "label": "Revalorisation de produits industriels"},
       |  {"codeROME": "K2305", "label": "Salubrit\u00e9 et traitement de nuisibles"},
       |  {"codeROME": "K2306", "label": "Supervision d'exploitation \u00e9co-industrielle"},
       |  {"codeROME": "K2401", "label": "Recherche en sciences de l'homme et de la soci\u00e9t\u00e9"},
       |  {"codeROME": "K2402", "label": "Recherche en sciences de l'univers, de la mati\u00e8re et du vivant"},
       |  {"codeROME": "K2501", "label": "Gardiennage de locaux"},
       |  {"codeROME": "K2502", "label": "Management de s\u00e9curit\u00e9 priv\u00e9e"},
       |  {"codeROME": "B1501", "label": "Fabrication et r\u00e9paration d'instruments de musique"},
       |  {"codeROME": "K2503", "label": "S\u00e9curit\u00e9 et surveillance priv\u00e9es"},
       |  {"codeROME": "K2601", "label": "Conduite d'op\u00e9rations fun\u00e9raires"},
       |  {"codeROME": "K2602", "label": "Conseil en services fun\u00e9raires"},
       |  {"codeROME": "K2603", "label": "Thanatopraxie"},
       |  {"codeROME": "L1101", "label": "Animation musicale et sc\u00e9nique"},
       |  {"codeROME": "L1102", "label": "Mannequinat et pose artistique"},
       |  {"codeROME": "L1103", "label": "Pr\u00e9sentation de spectacles ou d'\u00e9missions"},
       |  {"codeROME": "L1201", "label": "Danse"},
       |  {"codeROME": "L1202", "label": "Musique et chant"},
       |  {"codeROME": "B1601", "label": "M\u00e9tallerie d'art"},
       |  {"codeROME": "L1203", "label": "Art dramatique"},
       |  {"codeROME": "L1204", "label": "Arts du cirque et arts visuels"},
       |  {"codeROME": "L1301", "label": "Mise en sc\u00e8ne de spectacles vivants"},
       |  {"codeROME": "L1302", "label": "Production et administration spectacle, cin\u00e9ma et audiovisuel"},
       |  {"codeROME": "L1303", "label": "Promotion d'artistes et de spectacles"},
       |  {"codeROME": "L1304", "label": "R\u00e9alisation cin\u00e9matographique et audiovisuelle"},
       |  {"codeROME": "L1401", "label": "Sportif professionnel"},
       |  {"codeROME": "L1501", "label": "Coiffure et maquillage spectacle"},
       |  {"codeROME": "L1502", "label": "Costume et habillage spectacle"},
       |  {"codeROME": "L1503", "label": "D\u00e9cor et accessoires spectacle"},
       |  {"codeROME": "B1602", "label": "R\u00e9alisation d'objets artistiques et fonctionnels en verre"},
       |  {"codeROME": "L1504", "label": "\u00c9clairage spectacle"},
       |  {"codeROME": "L1505", "label": "Image cin\u00e9matographique et t\u00e9l\u00e9visuelle"},
       |  {"codeROME": "L1506", "label": "Machinerie spectacle"},
       |  {"codeROME": "L1507", "label": "Montage audiovisuel et post-production"},
       |  {"codeROME": "L1508", "label": "Prise de son et sonorisation"},
       |  {"codeROME": "L1509", "label": "R\u00e9gie g\u00e9n\u00e9rale"},
       |  {"codeROME": "M1101", "label": "Achats"},
       |  {"codeROME": "M1102", "label": "Direction des achats"},
       |  {"codeROME": "M1201", "label": "Analyse et ing\u00e9nierie financi\u00e8re"},
       |  {"codeROME": "M1202", "label": "Audit et contr\u00f4le comptables et financiers"},
       |  {"codeROME": "B1603", "label": "R\u00e9alisation d'ouvrages en bijouterie, joaillerie et orf\u00e8vrerie"},
       |  {"codeROME": "M1203", "label": "Comptabilit\u00e9"},
       |  {"codeROME": "M1204", "label": "Contr\u00f4le de gestion"},
       |  {"codeROME": "M1205", "label": "Direction administrative et financi\u00e8re"},
       |  {"codeROME": "M1206", "label": "Management de groupe ou de service comptable"},
       |  {"codeROME": "M1207", "label": "Tr\u00e9sorerie et financement"},
       |  {"codeROME": "M1301", "label": "Direction de grande entreprise ou d'\u00e9tablissement public"},
       |  {"codeROME": "M1302", "label": "Direction de petite ou moyenne entreprise"},
       |  {"codeROME": "M1401", "label": "Conduite d'enqu\u00eates"},
       |  {"codeROME": "N4401", "label": "Circulation du r\u00e9seau ferr\u00e9"},
       |  {"codeROME": "M1402", "label": "Conseil en organisation et management d'entreprise"},
       |  {"codeROME": "M1403", "label": "\u00c9tudes et prospectives socio-\u00e9conomiques"},
       |  {"codeROME": "B1604", "label": "R\u00e9paration - montage en syst\u00e8mes horlogers"},
       |  {"codeROME": "M1404", "label": "Management et gestion d'enqu\u00eates"},
       |  {"codeROME": "M1501", "label": "Assistanat en ressources humaines"},
       |  {"codeROME": "M1502", "label": "D\u00e9veloppement des ressources humaines"},
       |  {"codeROME": "M1503", "label": "Management des ressources humaines"},
       |  {"codeROME": "M1601", "label": "Accueil et renseignements"},
       |  {"codeROME": "M1602", "label": "Op\u00e9rations administratives"},
       |  {"codeROME": "M1603", "label": "Distribution de documents"},
       |  {"codeROME": "M1604", "label": "Assistanat de direction"},
       |  {"codeROME": "M1605", "label": "Assistanat technique et administratif"},
       |  {"codeROME": "M1606", "label": "Saisie de donn\u00e9es"},
       |  {"codeROME": "B1701", "label": "Conservation et reconstitution d'esp\u00e8ces animales"},
       |  {"codeROME": "M1607", "label": "Secr\u00e9tariat"},
       |  {"codeROME": "M1608", "label": "Secr\u00e9tariat comptable"},
       |  {"codeROME": "M1609", "label": "Secr\u00e9tariat et assistanat m\u00e9dical ou m\u00e9dico-social"},
       |  {"codeROME": "M1701", "label": "Administration des ventes"},
       |  {"codeROME": "M1702", "label": "Analyse de tendance"},
       |  {"codeROME": "M1703", "label": "Management et gestion de produit"},
       |  {"codeROME": "M1704", "label": "Management relation client\u00e8le"},
       |  {"codeROME": "M1705", "label": "Marketing"},
       |  {"codeROME": "M1706", "label": "Promotion des ventes"},
       |  {"codeROME": "M1707", "label": "Strat\u00e9gie commerciale"},
       |  {"codeROME": "B1801", "label": "R\u00e9alisation d'articles de chapellerie"},
       |  {"codeROME": "M1801", "label": "Administration de syst\u00e8mes d'information"},
       |  {"codeROME": "M1802", "label": "Expertise et support en syst\u00e8mes d'information"},
       |  {"codeROME": "M1803", "label": "Direction des syst\u00e8mes d'information"},
       |  {"codeROME": "M1804", "label": "\u00c9tudes et d\u00e9veloppement de r\u00e9seaux de t\u00e9l\u00e9coms"},
       |  {"codeROME": "M1805", "label": "\u00c9tudes et d\u00e9veloppement informatique"},
       |  {"codeROME": "M1806", "label": "Conseil et ma\u00eetrise d'ouvrage en syst\u00e8mes d'information"},
       |  {"codeROME": "M1807", "label": "Exploitation de syst\u00e8mes de communication et de commandement"},
       |  {"codeROME": "M1808", "label": "Information g\u00e9ographique"},
       |  {"codeROME": "M1809", "label": "Information m\u00e9t\u00e9orologique"},
       |  {"codeROME": "M1810", "label": "Production et exploitation de syst\u00e8mes d'information"},
       |  {"codeROME": "B1802", "label": "R\u00e9alisation d'articles en cuir et mat\u00e9riaux souples (hors v\u00eatement)"},
       |  {"codeROME": "N1101", "label": "Conduite d'engins de d\u00e9placement des charges"},
       |  {"codeROME": "N1102", "label": "D\u00e9m\u00e9nagement"},
       |  {"codeROME": "N1103", "label": "Magasinage et pr\u00e9paration de commandes"},
       |  {"codeROME": "N1104", "label": "Manoeuvre et conduite d'engins lourds de manutention"},
       |  {"codeROME": "N1105", "label": "Manutention manuelle de charges"},
       |  {"codeROME": "N1201", "label": "Affr\u00e8tement transport"},
       |  {"codeROME": "N1202", "label": "Gestion des op\u00e9rations de circulation internationale des marchandises"},
       |  {"codeROME": "N1301", "label": "Conception et organisation de la cha\u00eene logistique"},
       |  {"codeROME": "N1302", "label": "Direction de site logistique"},
       |  {"codeROME": "N1303", "label": "Intervention technique d'exploitation logistique"},
       |  {"codeROME": "B1803", "label": "R\u00e9alisation de v\u00eatements sur mesure ou en petite s\u00e9rie"},
       |  {"codeROME": "N2101", "label": "Navigation commerciale a\u00e9rienne"},
       |  {"codeROME": "N2102", "label": "Pilotage et navigation technique a\u00e9rienne"},
       |  {"codeROME": "N2201", "label": "Personnel d'escale a\u00e9roportuaire"},
       |  {"codeROME": "N2202", "label": "Contr\u00f4le de la navigation a\u00e9rienne"},
       |  {"codeROME": "N2203", "label": "Exploitation des pistes a\u00e9roportuaires"},
       |  {"codeROME": "N2204", "label": "Pr\u00e9paration des vols"},
       |  {"codeROME": "N2205", "label": "Direction d'escale et exploitation a\u00e9roportuaire"},
       |  {"codeROME": "N3101", "label": "Encadrement de la navigation maritime"},
       |  {"codeROME": "N3102", "label": "Equipage de la navigation maritime"},
       |  {"codeROME": "N3103", "label": "Navigation fluviale"},
       |  {"codeROME": "B1804", "label": "R\u00e9alisation d'ouvrages d'art en fils"},
       |  {"codeROME": "N3201", "label": "Exploitation des op\u00e9rations portuaires et du transport maritime"},
       |  {"codeROME": "N3202", "label": "Exploitation du transport fluvial"},
       |  {"codeROME": "N3203", "label": "Manutention portuaire"},
       |  {"codeROME": "N4101", "label": "Conduite de transport de marchandises sur longue distance"},
       |  {"codeROME": "N4102", "label": "Conduite de transport de particuliers"},
       |  {"codeROME": "N4103", "label": "Conduite de transport en commun sur route"},
       |  {"codeROME": "N4104", "label": "Courses et livraisons express"},
       |  {"codeROME": "N4105", "label": "Conduite et livraison par tourn\u00e9es sur courte distance"},
       |  {"codeROME": "N4201", "label": "Direction d'exploitation des transports routiers de marchandises"},
       |  {"codeROME": "N4202", "label": "Direction d'exploitation des transports routiers de personnes"},
       |  {"codeROME": "B1805", "label": "Stylisme"},
       |  {"codeROME": "N4203", "label": "Intervention technique d'exploitation des transports routiers de marchandises"},
       |  {"codeROME": "N4204", "label": "Intervention technique d'exploitation des transports routiers de personnes"},
       |  {"codeROME": "N4301", "label": "Conduite sur rails"},
       |  {"codeROME": "N4302", "label": "Contr\u00f4le des transports en commun"},
       |  {"codeROME": "N4402", "label": "Exploitation et manoeuvre des remont\u00e9es m\u00e9caniques"},
       |  {"codeROME": "N4403", "label": "Manoeuvre du r\u00e9seau ferr\u00e9"},
       |  {"codeROME": "B1806", "label": "Tapisserie - d\u00e9coration en ameublement"},
       |  {"codeROME": "C1101", "label": "Conception - d\u00e9veloppement produits d'assurances"},
       |  {"codeROME": "C1102", "label": "Conseil client\u00e8le en assurances"},
       |  {"codeROME": "C1103", "label": "Courtage en assurances"},
       |  {"codeROME": "C1104", "label": "Direction d'exploitation en assurances"},
       |  {"codeROME": "C1105", "label": "\u00c9tudes actuarielles en assurances"},
       |  {"codeROME": "A1101", "label": "Conduite d'engins agricoles et forestiers"},
       |  {"codeROME": "C1106", "label": "Expertise risques en assurances"},
       |  {"codeROME": "C1107", "label": "Indemnisations en assurances"},
       |  {"codeROME": "C1108", "label": "Management de groupe et de service en assurances"},
       |  {"codeROME": "C1109", "label": "R\u00e9daction et gestion en assurances"},
       |  {"codeROME": "C1110", "label": "Souscription d'assurances"},
       |  {"codeROME": "C1201", "label": "Accueil et services bancaires"},
       |  {"codeROME": "C1202", "label": "Analyse de cr\u00e9dits et risques bancaires"},
       |  {"codeROME": "C1203", "label": "Relation clients banque/finance"},
       |  {"codeROME": "C1204", "label": "Conception et expertise produits bancaires et financiers"},
       |  {"codeROME": "C1205", "label": "Conseil en gestion de patrimoine financier"},
       |  {"codeROME": "A1201", "label": "B\u00fbcheronnage et \u00e9lagage"},
       |  {"codeROME": "C1206", "label": "Gestion de client\u00e8le bancaire"},
       |  {"codeROME": "C1207", "label": "Management en exploitation bancaire"},
       |  {"codeROME": "C1301", "label": "Front office march\u00e9s financiers"},
       |  {"codeROME": "C1302", "label": "Gestion back et middle-office march\u00e9s financiers"},
       |  {"codeROME": "C1303", "label": "Gestion de portefeuilles sur les march\u00e9s financiers"},
       |  {"codeROME": "C1401", "label": "Gestion en banque et assurance"},
       |  {"codeROME": "C1501", "label": "G\u00e9rance immobili\u00e8re"},
       |  {"codeROME": "C1502", "label": "Gestion locative immobili\u00e8re"},
       |  {"codeROME": "C1503", "label": "Management de projet immobilier"},
       |  {"codeROME": "C1504", "label": "Transaction immobili\u00e8re"},
       |  {"codeROME": "A1202", "label": "Entretien des espaces naturels"},
       |  {"codeROME": "D1101", "label": "Boucherie"},
       |  {"codeROME": "D1102", "label": "Boulangerie - viennoiserie"},
       |  {"codeROME": "D1103", "label": "Charcuterie - traiteur"},
       |  {"codeROME": "D1104", "label": "P\u00e2tisserie, confiserie, chocolaterie et glacerie"},
       |  {"codeROME": "D1105", "label": "Poissonnerie"},
       |  {"codeROME": "D1106", "label": "Vente en alimentation"},
       |  {"codeROME": "D1107", "label": "Vente en gros de produits frais"},
       |  {"codeROME": "D1201", "label": "Achat vente d'objets d'art, anciens ou d'occasion"},
       |  {"codeROME": "D1202", "label": "Coiffure"},
       |  {"codeROME": "D1203", "label": "Hydroth\u00e9rapie"},
       |  {"codeROME": "A1203", "label": "Am\u00e9nagement et entretien des espaces verts"},
       |  {"codeROME": "D1204", "label": "Location de v\u00e9hicules ou de mat\u00e9riel de loisirs"},
       |  {"codeROME": "D1205", "label": "Nettoyage d'articles textiles ou cuirs"},
       |  {"codeROME": "D1206", "label": "R\u00e9paration d'articles en cuir et mat\u00e9riaux souples"},
       |  {"codeROME": "D1207", "label": "Retouches en habillement"},
       |  {"codeROME": "D1208", "label": "Soins esth\u00e9tiques et corporels"},
       |  {"codeROME": "D1209", "label": "Vente de v\u00e9g\u00e9taux"},
       |  {"codeROME": "D1210", "label": "Vente en animalerie"},
       |  {"codeROME": "D1211", "label": "Vente en articles de sport et loisirs"},
       |  {"codeROME": "D1212", "label": "Vente en d\u00e9coration et \u00e9quipement du foyer"},
       |  {"codeROME": "D1213", "label": "Vente en gros de mat\u00e9riel et \u00e9quipement"}
       |]
     """.stripMargin)
}
