import sbt.Artifact

// Récupération du nom du fichier .zip généré par SbtNativePackager
val zipTask = TaskKey[sbt.File]("publish-zip", "publish the zip generated by SbtNativePackager plugin")

zipTask := {
  sbt.file(target.value + "/universal/" + normalizedName.value + "-" + version.value + ".zip")
}

artifact in zipTask := {
  Artifact(normalizedName.value, `type` = "zip", extension = "zip")
}

// Ajoute un artefact representant le zip à la liste pour publication
addArtifact(artifact in zipTask, zipTask).settings

publish := (publish dependsOn dist).value