FROM openjdk:8-jre-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y install unzip && \
    apt-get -y install curl && \
    rm -rf /var/lib/apt/lists/*

# Make port 9000 available to the world outside this container
EXPOSE 9000

WORKDIR /opt/perspectives-webapp

ARG WEBAPP_LOGBACK_RESOURCE=logback.xml
ENV WEBAPP_LOGBACK_RESOURCE=${WEBAPP_LOGBACK_RESOURCE}

ARG WEBAPP_CONFIG_RESOURCE=application.conf
ENV WEBAPP_CONFIG_RESOURCE=${WEBAPP_CONFIG_RESOURCE}

COPY perspectives-webapp-*.zip ./perspectives-webapp.zip

RUN unzip perspectives-webapp.zip

RUN mv ./perspectives-webapp-* ./perspectives-webapp

RUN rm perspectives-webapp.zip

HEALTHCHECK --interval=15s --timeout=10s --start-period=60s CMD curl -f http://localhost:9000 || exit 1

COPY webapp_entrypoint.sh .

RUN chmod +x ./webapp_entrypoint.sh

ENTRYPOINT ["./webapp_entrypoint.sh"]
