FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    apt-get -y install cron && \
    apt-get -y install postgresql-client && \
    rm -rf /var/lib/apt/lists/*

ARG POSTGRES_DB=perspectives

ARG POSTGRES_USER=perspectives

ARG POSTGRES_PASSWORD=perspectives

ARG POSTGRES_HOST=database

ARG BACKUP_ROTATION_DAYS=30

RUN mkdir /opt/postgresql-cron-backup
RUN mkdir /var/opt/postgresql-cron-backup

RUN touch /var/log/cron.log

COPY postgresql-cron-backup/cron-postgresql-backup /etc/cron.d/

RUN chmod 0644 /etc/cron.d/cron-postgresql-backup

COPY postgresql-cron-backup/*.sh /opt/postgresql-cron-backup/

# Pour disposer des variables d'environnement nécessaires à pg_dump dans le contexte d'un cron
RUN echo "export PGUSER=${POSTGRES_USER}\n\
export PGPASSWORD=${POSTGRES_PASSWORD}\n\
export PGHOST=${POSTGRES_HOST}\n\
export PGDATABASE=${POSTGRES_DB}\n\
export BACKUP_DIR=/var/opt/postgresql-cron-backup\n\
export BACKUP_ROTATION_DAYS=${BACKUP_ROTATION_DAYS}" > /opt/postgresql-cron-backup/pgenv.sh

CMD ["cron", "-f"]