FROM openjdk:8-jre-slim

ARG DEBIAN_FRONTEND=noninteractive

# Common software : always run apt-get update et apt-get install in the same run statement
RUN apt-get update && \
    apt-get -y install unzip && \
    apt-get -y install curl && \
    rm -rf /var/lib/apt/lists/* # delete all the apt list files since they're big and get stale quickly

WORKDIR /opt/perspectives-batchs

ARG BATCHS_LOGBACK_RESOURCE=logback.xml
ENV BATCHS_LOGBACK_RESOURCE=${BATCHS_LOGBACK_RESOURCE}

ARG BATCHS_CONFIG_RESOURCE=application.conf
ENV BATCHS_CONFIG_RESOURCE=${BATCHS_CONFIG_RESOURCE}

ARG BATCHS_VERSION
ENV BATCHS_VERSION=${BATCHS_VERSION}

ARG EXPORT_POLEEMPLOI_DIRECTORY=/var/perspectives/export_poleemploi
ENV EXPORT_POLEEMPLOI_DIRECTORY=${EXPORT_POLEEMPLOI_DIRECTORY}

ARG EXPORT_POLEEMPLOI_ARCHIVE_DIRECTORY=/var/perspectives/export_poleemploi/archives
ENV EXPORT_POLEEMPLOI_ARCHIVE_DIRECTORY=${EXPORT_POLEEMPLOI_ARCHIVE_DIRECTORY}

RUN mkdir -p ${EXPORT_POLEEMPLOI_DIRECTORY}
RUN mkdir -p ${EXPORT_POLEEMPLOI_ARCHIVE_DIRECTORY}

COPY perspectives-batchs-${BATCHS_VERSION}.zip .

RUN unzip perspectives-batchs-${BATCHS_VERSION}.zip

HEALTHCHECK --interval=15s --timeout=10s --start-period=60s CMD curl -f http://localhost:9000 || exit 1

CMD ["sh", "-c", "./perspectives-batchs-${BATCHS_VERSION}/bin/perspectives-batchs -Dlogger.resource=${BATCHS_LOGBACK_RESOURCE} -Dconfig.resource=${BATCHS_CONFIG_RESOURCE}"]