FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    apt-get -y install cron && \
    apt-get -y install postgresql-client

ARG POSTGRES_DB=perspectives
ENV POSTGRES_DB=${POSTGRES_DB}

ARG POSTGRES_USER=perspectives
ENV POSTGRES_USER=${POSTGRES_USER}

ARG POSTGRES_PASSWORD=perspectives
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

ARG POSTGRES_HOST=database
ENV POSTGRES_HOST=${POSTGRES_HOST}

RUN mkdir /opt/postgresql-cron-backup
RUN mkdir /var/opt/postgresql-cron-backup

RUN touch /var/log/cron.log

COPY postgresql-cron-backup/cron-postgresql-backup /etc/cron.d/

RUN chmod 0644 /etc/cron.d/cron-postgresql-backup

COPY postgresql-cron-backup/*.sh /opt/postgresql-cron-backup/

# Pour disposer des variables d'environnement nécessaires à pg_dump dans le contexte d'un cron
RUN echo 'export PGUSER='${POSTGRES_USER}'\n\
export PGPASSWORD='${POSTGRES_PASSWORD}'\n\
export PGHOST='${POSTGRES_HOST}'\n\
export PGDATABASE='${POSTGRES_DB}'\n\
export BACKUP_DIR=/var/opt/postgresql-cron-backup' > /opt/postgresql-cron-backup/pgenv.sh

CMD ["cron", "-f"]